version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: horde-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./static:/app/static
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    image: nginx:alpine
    container_name: horde-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
